// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models_Context.Context;

#nullable disable

namespace Models_Context.Migrations
{
    [DbContext(typeof(RPGDarkSoulsDbContext))]
    [Migration("20251208220546_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArmorSet", b =>
                {
                    b.Property<int>("ArmorsArmorId")
                        .HasColumnType("int");

                    b.Property<int>("SetsSetId")
                        .HasColumnType("int");

                    b.HasKey("ArmorsArmorId", "SetsSetId");

                    b.HasIndex("SetsSetId");

                    b.ToTable("ArmorSet");
                });

            modelBuilder.Entity("Models_Context.Models.Armor", b =>
                {
                    b.Property<int>("ArmorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArmorId"));

                    b.Property<int?>("ArmorTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Poise")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Skin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ArmorId");

                    b.HasIndex("TypeId");

                    b.ToTable("Armors");
                });

            modelBuilder.Entity("Models_Context.Models.ArmorInfluence", b =>
                {
                    b.Property<int>("InfluenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InfluenceId"));

                    b.Property<int?>("ArmorId")
                        .HasColumnType("int");

                    b.Property<int?>("InfluenceType")
                        .HasColumnType("int");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InfluenceId");

                    b.HasIndex("ArmorId");

                    b.HasIndex("TypeId");

                    b.ToTable("ArmorInfluences");
                });

            modelBuilder.Entity("Models_Context.Models.ArmorType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<int?>("SlotId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeId");

                    b.HasIndex("SlotId")
                        .IsUnique()
                        .HasFilter("[SlotId] IS NOT NULL");

                    b.ToTable("ArmorTypes");
                });

            modelBuilder.Entity("Models_Context.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterId"));

                    b.Property<string>("CharactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Dexterity")
                        .HasColumnType("int");

                    b.Property<int?>("Endurance")
                        .HasColumnType("int");

                    b.Property<int?>("Faith")
                        .HasColumnType("int");

                    b.Property<int?>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<int?>("Strenght")
                        .HasColumnType("int");

                    b.Property<int?>("Vigor")
                        .HasColumnType("int");

                    b.HasKey("CharacterId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Models_Context.Models.InfluenceType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeId");

                    b.ToTable("InfluenceTypes");
                });

            modelBuilder.Entity("Models_Context.Models.Set", b =>
                {
                    b.Property<int>("SetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SetId"));

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SetId");

                    b.HasIndex("CharacterId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("Models_Context.Models.Slot", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SlotId");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("Models_Context.Models.Weapon", b =>
                {
                    b.Property<int>("WeaponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeaponId"));

                    b.Property<decimal?>("Damage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReqDexterity")
                        .HasColumnType("int");

                    b.Property<int?>("ReqFaith")
                        .HasColumnType("int");

                    b.Property<int?>("ReqIntelligence")
                        .HasColumnType("int");

                    b.Property<int?>("ReqStrenght")
                        .HasColumnType("int");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.Property<int?>("WeaponTypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("WeaponId");

                    b.HasIndex("TypeId");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("Models_Context.Models.WeaponIfnluence", b =>
                {
                    b.Property<int>("InfluenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InfluenceId"));

                    b.Property<int?>("InfluenceTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("InfluenceId");

                    b.HasIndex("TypeId");

                    b.HasIndex("WeaponId");

                    b.ToTable("WeaponIfnluences");
                });

            modelBuilder.Entity("Models_Context.Models.WeaponType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<int?>("SlotId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeId");

                    b.HasIndex("SlotId")
                        .IsUnique()
                        .HasFilter("[SlotId] IS NOT NULL");

                    b.ToTable("WeaponTypes");
                });

            modelBuilder.Entity("SetWeapon", b =>
                {
                    b.Property<int>("SetsSetId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponsWeaponId")
                        .HasColumnType("int");

                    b.HasKey("SetsSetId", "WeaponsWeaponId");

                    b.HasIndex("WeaponsWeaponId");

                    b.ToTable("SetWeapon");
                });

            modelBuilder.Entity("ArmorSet", b =>
                {
                    b.HasOne("Models_Context.Models.Armor", null)
                        .WithMany()
                        .HasForeignKey("ArmorsArmorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models_Context.Models.Set", null)
                        .WithMany()
                        .HasForeignKey("SetsSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models_Context.Models.Armor", b =>
                {
                    b.HasOne("Models_Context.Models.ArmorType", "ArmorType")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("ArmorType");
                });

            modelBuilder.Entity("Models_Context.Models.ArmorInfluence", b =>
                {
                    b.HasOne("Models_Context.Models.Armor", "Armor")
                        .WithMany("ArmorInfluences")
                        .HasForeignKey("ArmorId");

                    b.HasOne("Models_Context.Models.InfluenceType", "Influence")
                        .WithMany("ArmorInfluences")
                        .HasForeignKey("TypeId");

                    b.Navigation("Armor");

                    b.Navigation("Influence");
                });

            modelBuilder.Entity("Models_Context.Models.ArmorType", b =>
                {
                    b.HasOne("Models_Context.Models.Slot", "Slot")
                        .WithOne("ArmorType")
                        .HasForeignKey("Models_Context.Models.ArmorType", "SlotId");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("Models_Context.Models.Set", b =>
                {
                    b.HasOne("Models_Context.Models.Character", "Character")
                        .WithMany("Sets")
                        .HasForeignKey("CharacterId");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Models_Context.Models.Weapon", b =>
                {
                    b.HasOne("Models_Context.Models.WeaponType", "WeaponType")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("WeaponType");
                });

            modelBuilder.Entity("Models_Context.Models.WeaponIfnluence", b =>
                {
                    b.HasOne("Models_Context.Models.InfluenceType", "InfluenceType")
                        .WithMany("WeaponIfnluences")
                        .HasForeignKey("TypeId");

                    b.HasOne("Models_Context.Models.Weapon", "Weapon")
                        .WithMany("WeaponInfluences")
                        .HasForeignKey("WeaponId");

                    b.Navigation("InfluenceType");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("Models_Context.Models.WeaponType", b =>
                {
                    b.HasOne("Models_Context.Models.Slot", "Slot")
                        .WithOne("WeaponType")
                        .HasForeignKey("Models_Context.Models.WeaponType", "SlotId");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("SetWeapon", b =>
                {
                    b.HasOne("Models_Context.Models.Set", null)
                        .WithMany()
                        .HasForeignKey("SetsSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models_Context.Models.Weapon", null)
                        .WithMany()
                        .HasForeignKey("WeaponsWeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models_Context.Models.Armor", b =>
                {
                    b.Navigation("ArmorInfluences");
                });

            modelBuilder.Entity("Models_Context.Models.Character", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("Models_Context.Models.InfluenceType", b =>
                {
                    b.Navigation("ArmorInfluences");

                    b.Navigation("WeaponIfnluences");
                });

            modelBuilder.Entity("Models_Context.Models.Slot", b =>
                {
                    b.Navigation("ArmorType");

                    b.Navigation("WeaponType");
                });

            modelBuilder.Entity("Models_Context.Models.Weapon", b =>
                {
                    b.Navigation("WeaponInfluences");
                });
#pragma warning restore 612, 618
        }
    }
}
